name: itvlist

on:
  schedule:
    - cron: '0 10,22 * * *'
    
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-22.04@20240422.1.0
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
         run: pip install selenium requests futures eventlet aiohttp aiofiles
      - name: Run ZHGXTVHN
        run: python ${{ github.workspace }}/ZHGXTVHN.py
                
              
      - name: 提交更改
        run: |
          git config --local user.email "15857674@qq.com"
          git config --local user.name "seadai794"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
