name: itvlist

on:
  schedule:
    - cron: '0 10,22 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install selenium requests futures eventlet aiohttp aiofiles

      - name: Run ZHGXTVHN
        run: python ZHGXTVHN.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "15857674@qq.com"
          git config --global user.name "seadai794"
          git add *.txt *.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-commit generated files"
          git push
